### ISSUE TITLE
"from macos_tags import Tag, Color" causes NameError

### ISSUE THREAD

**Issue by workflowsguy** [dmkskn/macos-tags#7]
When working through the examples in the documentation, the variant with importing "Tag" and "Color" does not work as described. I get the following:

```
Python 3.7.6 (default, Dec 30 2019, 19:38:36) 
[Clang 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license()" for more information.
WARNING: The version of Tcl/Tk (8.5.9) in use may be unstable. Visit
http://www.python.org/download/mac/tcltk/ for current information.
>>> from macos_tags import Tag, Color
>>> path = "/Users/guy/temp/30.10.2019.txt"
>>> tag = Tag(name="python", color=Color.GREEN)
>>> macos_tags.add(tag, file=path)
Traceback (most recent call last):
  File "<pyshell#3>", line 1, in <module>
    macos_tags.add(tag, file=path)
NameError: name 'macos_tags' is not defined
```

From experimenting, I found out that including either `import macos_tags` or `from macos_tags import Tag, Color` is not sufficient. I have to include both in my program to get it working.
Is there a reason why this is necessary? If so, I suggest mentioning it in the docs.

Thanks!

**Comment by dmkskn** [comment]
Yes there is a reason. [It's how import in Python works](https://realpython.com/absolute-vs-relative-python-imports/#syntax-of-import-statements). 🤷‍♂️

You can import a package. 

```python
import macos_tags

tag = macos_tags.Tag(name="python", color=macos_tags.Color.GREEN))
macos_tags.add(tag, file=path)

```

You can import from package.

```python
from macos_tags import Tag, Color, add

tag = Tag(name="python", color=Color.GREEN))
add(tag, file=path)
```

Or you can import all objects and functions from the package (anti-pattern).

```python
from macos_tags import * 

tag = Tag(name="python", color=Color.GREEN))
add(tag, file=path)
```

### PS
It is best to use the first option and, if you like, combine it with the second (to make code more readable). 

If you don't want to use absolute and relative imports at the same time you can do something like this.

```python
import macos_tags

Tag = macos_tags.Tag
Color = macos_tags.Color

tag = Tag(name="python", color=Color.GREEN))
macos_tags.add(tag, file=path)
```

But the two import statements look much better.

```python
import macos_tags
from macos_tags import Color, Tag

tag = Tag(name="python", color=Color.GREEN))
macos_tags.add(tag, file=path)
```

👋
